In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import plotly.graph_objects as go

In [22]:
L = 1
N = 6
h = (L / N)

# Create the array of vertices, xyz indexing.
V_ind = np.asarray([[[[i,j,k] for k in range(N)] for j in range(N)] for i in range(N)])
V = V_ind * h
V.shape

(6, 6, 6, 3)

In [26]:
V_ind

array([[[[0, 0, 0],
         [0, 0, 1],
         [0, 0, 2],
         [0, 0, 3],
         [0, 0, 4],
         [0, 0, 5]],

        [[0, 1, 0],
         [0, 1, 1],
         [0, 1, 2],
         [0, 1, 3],
         [0, 1, 4],
         [0, 1, 5]],

        [[0, 2, 0],
         [0, 2, 1],
         [0, 2, 2],
         [0, 2, 3],
         [0, 2, 4],
         [0, 2, 5]],

        [[0, 3, 0],
         [0, 3, 1],
         [0, 3, 2],
         [0, 3, 3],
         [0, 3, 4],
         [0, 3, 5]],

        [[0, 4, 0],
         [0, 4, 1],
         [0, 4, 2],
         [0, 4, 3],
         [0, 4, 4],
         [0, 4, 5]],

        [[0, 5, 0],
         [0, 5, 1],
         [0, 5, 2],
         [0, 5, 3],
         [0, 5, 4],
         [0, 5, 5]]],


       [[[1, 0, 0],
         [1, 0, 1],
         [1, 0, 2],
         [1, 0, 3],
         [1, 0, 4],
         [1, 0, 5]],

        [[1, 1, 0],
         [1, 1, 1],
         [1, 1, 2],
         [1, 1, 3],
         [1, 1, 4],
         [1, 1, 5]],

        [[1, 2, 0],
  

In [20]:
integers = np.round(np.array([[13, 15.8, 1.3], [13, 40, 1]]) / 10).astype(int)
integers

array([[1, 2, 0],
       [1, 4, 0]])

In [38]:
V_ind[integers[:, 0], integers[:, 1], integers[:, 2]]

array([[1, 2, 0],
       [1, 4, 0]])